version: '3.4'

services: 
  backend:
    build: .
    expose: 
      - "80"
  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - backend
    ports:
      - "4000:4000"