version: '3.4'

services: 
  kestrel:
    build: .
    expose: 
      - "80"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - kestrel
    ports:
      - "80:80"